spring.application.name=HospitalSystem

# Server Port (Supports hosting dynamic port)
server.port=${PORT:8080}

# MongoDB Atlas Database Configuration
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb+srv://rakhadaivanda_db_user:pcwRoi9oPED1sv3j@cluster0.ukgyx1n.mongodb.net/hospital_db?retryWrites=true&w=majority&appName=Cluster0&connectTimeoutMS=10000&socketTimeoutMS=10000&serverSelectionTimeoutMS=10000}
spring.data.mongodb.database=${MONGODB_DATABASE:hospital_db}

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Show SQL/Mongo Queries (for debugging)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=INFO
